### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by Shisunlel** [Shisunlel/khemarak-lyrics-vue#2]
Song Lyrics Page
- [x]  **move to vite or nuxt**
- [ ] add contributor name
- [ ] related songs from artist
- [ ] artist description
- [ ] songs from same album if exist
- [ ] load more or paginate
- [ ] youtube url (low chance)

**Comment by Shisunlel** [comment]
vite done 01-10-22
